# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jason/Development/X16/Vera/X16Community_ArtixDVI/x16CommunityVera/vivado/MercuryII_X16Community_Vera/MercuryII_X16Community_Vera.srcs/sources_1/ip/palette_ram/palette_ram.xci
# IP: The module: 'palette_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jason/Development/X16/Vera/X16Community_ArtixDVI/x16CommunityVera/vivado/MercuryII_X16Community_Vera/MercuryII_X16Community_Vera.gen/sources_1/ip/palette_ram/palette_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'palette_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Jason/Development/X16/Vera/X16Community_ArtixDVI/x16CommunityVera/vivado/MercuryII_X16Community_Vera/MercuryII_X16Community_Vera.srcs/sources_1/ip/palette_ram/palette_ram.xci
# IP: The module: 'palette_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jason/Development/X16/Vera/X16Community_ArtixDVI/x16CommunityVera/vivado/MercuryII_X16Community_Vera/MercuryII_X16Community_Vera.gen/sources_1/ip/palette_ram/palette_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'palette_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
